Adenium/Models/Shared/LookupListResponse.cs
using System;
using System.Collections.Generic;
using BusinessObjectsLibrary;
using BusinessServiceLibrary;

namespace Adenium.Models.SharedApi
{

    
    public class LookupListResponse : ResponseBase
    {

      
        public List<ListItem> ListItems { get; set; }

        public LookupListResponse(StatusObject status, string listName)
            : base(status)
        {
            try
            {
               
               

                var service = new SharedService(status);
                ListItems = service.GetLookupList(listName);


                status.StatusMessage = "List Items Retrieved";
                status.Success = true;
            }
            catch (Exception ex)
            {
                status.StatusMessage = ex.Message;
                status.Success = false;
            }

        }
       

    }
    
 
}

Adenium/Controllers/ApiUrlController.cs
using DataAccessLibrary;
using System.Web.Mvc;

namespace AllAdmin.Controllers
{
    public class RequestModel
    {
        public string site { get; set; }
    }

    public class ApiUrlController : Controller
    {
        public string Get()
        {
          
            return EpsUrlService.EpsUrl;
        }

        public ActionResult SetEpsUrl()
        {
            return View();
        }
        
        public string Roles()
        {
            string[] roleNames = System.Web.Security.Roles.GetRolesForUser();
            if (roleNames.Length > 0)
                return string.Format("   role: {0}", roleNames[0]);
            return "";
        }
    }
}

Adenium/Controllers/ClientController.cs
using System.Web.Mvc;


namespace Adenium.Controllers.API
{
     [Authorize]
    public class ClientController : Controller
    {
        public ActionResult ClientList()
        {
                       
            return View();
        }
        public ActionResult ClientDetail()
        {

            return View();
        }
    }
}

Adenium/Controllers/ContractController.cs
using System.Web.Mvc;

namespace Adenium.Controllers
{
    [Authorize]
    public class ContractController : Controller
    {
        //
        // GET: /Accounting/

        public ActionResult ConsultantList()
        {
            return View();
        }
        public ActionResult ConsultantDetail()
        {
            return View();
        }
        public ActionResult ContractList()
        {
            return View();
        }
        public ActionResult ContractDetail()
        {
            return View();
        }
    }
}

Adenium/Controllers/ReportsController.cs
using Microsoft.Reporting.WebForms;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace Adenium.Controllers
{
    [Authorize]
    public class ReportsController : Controller
    {
        private string reportServer = "";
        private Uri reportServerURI;
        private string SSRSUserName = "";
        private string SSRSPassword = "";
        private string SSRSDomain = "";
        private string reportPath = "";

        private bool SetSSRSParamters()
        {
            var appSettingsReader = new System.Configuration.AppSettingsReader();
            reportServer = (string)appSettingsReader.GetValue("SSRSReportServer", typeof(string));
            reportServerURI = new Uri(reportServer);
            reportPath = (string)appSettingsReader.GetValue("SSRSReportPath", typeof(string));
            SSRSUserName = (string)appSettingsReader.GetValue("SSRSUserName", typeof(string));
            SSRSPassword = (string)appSettingsReader.GetValue("SSRSPassword", typeof(string));
            SSRSDomain = (string)appSettingsReader.GetValue("SSRSDomain", typeof(string));
            return true;
        }

        private ReportViewer reportViewer = new ReportViewer()
        {
            ProcessingMode = ProcessingMode.Remote,
            SizeToReportContent = true,
            Width = Unit.Pixel(1094),
            Height = Unit.Pixel(300),
            AsyncRendering = false,
            ShowParameterPrompts = false,
            ZoomMode = ZoomMode.FullPage,
            BackColor = System.Drawing.Color.White
        };



      
        public ActionResult OrderReport()
        {
            {
         
                return View();
            }
           
        }
        public ActionResult BookingsReport()
        {
            {

                return View();
            }

        }
        public ActionResult GreenFuseBreederReport()
        {
            {

                return View();
            }

        }
        public ActionResult YearOverYearReport()
        {
            {
                return View();
            }

        }

      

        //[HttpPost]
        //[ActionName("RunYearOverYearReport")]
        //public PartialViewResult RunYearOverYearReport(
        //string cboGrowerName,
        //string cboSupplierName,
        //string cboBrokerName
        // )
        //{
        //    string reportName = "Year Over Year Report";
        //    bool bRet = SetSSRSParamters();

        //    //Set up Viewer
        //    reportViewer.ServerReport.ReportPath = reportPath + reportName;
        //    reportViewer.ServerReport.ReportServerUrl = reportServerURI;

        //    //Set up Credentials

        //    IReportServerCredentials irsc = new CustomReportCredentials(SSRSUserName, SSRSPassword, SSRSDomain);
        //    // var irsc = new CustomReportCredentials(SSRSUserName, SSRSPassword, SSRSDomain);
        //    reportViewer.ServerReport.ReportServerCredentials = irsc;

        //    //Set up Parameters
        //    List<ReportParameter> reportParameters = new List<ReportParameter>();
        //    reportParameters.Add(new ReportParameter("pGrowerGuid", cboGrowerName));
        //    reportParameters.Add(new ReportParameter("pSupplierGuid", cboSupplierName));
        //    reportParameters.Add(new ReportParameter("pBrokerGuid", cboBrokerName));


        //    reportViewer.ServerReport.SetParameters(reportParameters);

        //    //Run the report
        //    reportViewer.ServerReport.Refresh();

        //    //Return Viewer
        //    ViewBag.ReportViewer = reportViewer;
        //    ViewBag.ReportToShow = true;
        //    return PartialView("~/Views/Shared/_ReportViewer.cshtml");
        //}

        public ActionResult OpenInvoiceReport()
        {
            {
                return View();
            }

        }

        
       
        public ActionResult B2BAvailability()
        {
            {

                return View();
            }

        }
     
        public ActionResult DummenAvailGap()
        {
            {

                return View();
            }

        }
        public ActionResult Searches()
        {
            {

                return View();
            }

        }
        public ActionResult SupplierReport()
        {
            {

                return View();
            }

        }
        public ActionResult B2BErrorListReport()
        {
            {

                return View();
            }

        }
        public ActionResult ProductFormSalesQtyQAReport()
        {
            {

                return View();
            }

        }

        public ActionResult GrowerReport()
        {
            {

                return View();
            }

        }
        public ActionResult GrowerProductListReport()
        {
            {

                return View();
            }

        }
        public ActionResult DummenQuoteSummary()
        {
            {

                return View();
            }
        }
        public ActionResult DummenZeroPrice()
        {
            {

                return View();
            }

        }    
           public ActionResult GeneticOwnerURC()
        {
            {

                return View();
            }

        }
        

       
        


    }
    
}

Adenium/Controllers/api/SharedController.cs
using Adenium.Models.SharedApi;
using BusinessObjectsLibrary;
using System;
using System.Web;
using System.Web.Http;
using System.Web.Http.Description;

namespace Adenium.Controllers.SharedApi
{
    [RoutePrefix("api/Shared")]
    public class SharedController : ApiController
    {
        [Route("LookupList"), ActionName("LookupList"), HttpGet]
        public LookupListResponse LookupList(string listName)
        {
            var userName = User.Identity.Name;
            var status = new StatusObject(userName);

            var model = new LookupListResponse(status, listName);
            return model;

        }
      
    }

}

Adenium/Views/Shared/SetEpsUrl.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "SetEpsUrl";
}

@section styles {
        

    <link href="~/Content/styles/eps_tools.css" rel="stylesheet" />

}

    <div>
        <h2>Change Green-Fuse Site</h2>
        <select id="listing" name="ePS Site" onchange="changeSite(this);">
        <option value="" style="display:none;"></option>
        <option id ="0" >Development</option>
        <option id ="1" >Production</option>
        @*<option id ="3" >Local</option>*@
        </select>
    </div>

@section scripts {
    <script src="~/Scripts/eps_tools.js"></script>


    <script>
        function changeSite(sel) {
            var value = sel.options[sel.selectedIndex].value;
            $.get("/ApiUrlApi/ChangeEpsUrl",  { site: value } )
                .done(function(data) {
                    var element = $("#listing");
                    
                    $("#labelEnvironment").html(data.substring(24,data.length));
                    viewModelFloatMessage(element, data, 2500);

                   // location.reload();
                });
        }
    </script>
}

Adenium/Views/Shared/_ApiSite.cshtml
@*@Html.ActionLink("Set Environment", "SetEpsUrl", "ApiUrl", new { ID = "ApiUrl" }, new { @class = "action_buttons" })*@
<div id="labelEnvironment" style="display:inline">@{Html.RenderAction("Get", "ApiUrl");}</div>
<br />
<div style="display:inline;">@{Html.RenderAction("Roles", "ApiUrl");}</div>

Adenium/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=9; IE=8; IE=7; IE=EDGE" />
    <meta charset="utf-8" />
    @{
        var appSettingsReader_2 = new System.Configuration.AppSettingsReader();
        Session["SoftwareOwner"] = (string)appSettingsReader_2.GetValue("SoftwareOwner", typeof(string)).ToString().ToUpper();
        var softwareOwner_2 = Session["SoftwareOwner"].ToString();
     
         <link href="~/Images/AdeniumLogo.jpg" rel="shortcut icon" type="image/x-icon" />
        
    }

    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
    <link href="~/Content/layout.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")

    @RenderSection("styles", required: false)

    @Scripts.Render("~/bundles/modernizr")

    <script type="text/javascript">

        sfHover = function () {
            var sfEls = document.getElementById("nav").getElementsByTagName("LI");
            for (var i = 0; i < sfEls.length; i++) {
                sfEls[i].onmouseover = function () {
                    this.className += " sfhover";
                }
                sfEls[i].onmouseout = function () {
                    this.className = this.className.replace(new RegExp(" sfhover\\b"), "");
                }
            }
        }
        if (window.attachEvent) window.attachEvent("onload", sfHover);

    </script>

</head>
    <body>
        <header>
            <div class="scott-header">
                
                <table style="width:100%">
                    <tr>
                        <td>
                            <a style="border:none;" href="../../">
                                @{
                                    var softwareOwner_1 = Session["SoftwareOwner"].ToString();
                                    
                                    if (softwareOwner_1 == "ADE")

                                    {
                                        <span><img style="border:none;" src="~/Images/AdeniumLogo.jpg" alt="adenium logo" /> </span>
                                        <input id="txtSoftwareOwner" type="text" value="ADE" style="display:none" />
                                    }
                                }

                            </a>
                        </td>

                        <td>
                            <div id="login" class="login_upper_right">
                                @Html.Partial("_LoginPartial")
                                @Html.Partial("_ApiSite")
                            </div>
                        </td>
                    </tr>
                    <tr>
                        <td valign="bottom">
                            <ul id="nav">

                                <li>
                                    <a href="#">Dashboards</a>
                                    <ul id="Dashboard_menu_list">
                                        @{
                                            var softwareOwner6 = Session["SoftwareOwner"].ToString();
                                            switch (softwareOwner6)
                                            {
                                               
                                                case "ADE":
                                                    {
                                                        <li>@Html.ActionLink("Adenium Dashboard", "ADEDashboard", "Dashboards")</li>                                                     
                                                        break;
                                                    }
                                                default:
                                                    {
                                                        break;
                                                    }
                                            }
                                        }
                                    </ul>
                                </li>

                                <li>
                                    <a href="#">Time Entry</a>
                                    <ul id="TimeEntry_menu_list">
                                        <li>@Html.ActionLink("Reported Hours", "ReportedHoursList", "TimeEntry")</li>
                                        



                                    </ul>
                                </li>
                                <li>
                                    <a href="#">Contracts</a>
                                    <ul id="Contracts_menu_list">

                                        <li>@Html.ActionLink("Consultants", "ConsultantList", "Contract")</li>
                                        <li>@Html.ActionLink("Contracts", "ContractList", "Contract")</li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="#">Clients</a>
                                    <ul id="Clients_menu_list">
                                        <li>@Html.ActionLink("Client List", "ClientList", "Client")</li>
                                    </ul>
                                </li>
                                

                                <li>
                                    <a href="#">Reports</a>
                                    <ul id="Reports_menu_list">
                                      
                                        <li>@Html.ActionLink("What Runs When Report", "WhatRunsWhenReport", "Reports")</li>
                                    </ul>
                                </li>
                            </ul>
                        </td>
                        <td></td>
                    </tr>


                </table>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            @*<section class="content-wrapper main-content clear-fix">*@
            <section class="">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    @{
                        var softwareOwner8 = Session["SoftwareOwner"].ToString();
                        switch (softwareOwner8.ToUpper())
                        {
                           
                            case "ADE":
                                {
                                    <p>&copy; @DateTime.Now.Year - Adenium.com</p>
                                    break;
                                }
                            default:
                                {
                                    break;
                                }
                        }
                      
                      
                    }
                </div>
            </div>
        </footer>
        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

Adenium/Views/Shared/_ReportViewer.cshtml
@using ReportViewerForMvc;
@Html.ReportViewer(ViewBag.ReportViewer as Microsoft.Reporting.WebForms.ReportViewer, new { @class = "SSRSReport", @style = "overflow: hidden !important;" })